name: Scrape Website

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Install Chrome
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y chromium-browser

    # - name: Download Chromedriver
    #   run: |
    #     sudo apt-get install -y unzip
    #     wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_linux64.zip
    #     unzip /tmp/chromedriver.zip -d /usr/local/bin/
    #     sudo ln -s /usr/local/bin/chromedriver /usr/bin/chromedriver

    - name: Run scraping script
      run: python scrape.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add data/
        git commit -m 'Update scraped data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


